import com.badlogic.gdx.Gdx
import com.badlogic.gdx.graphics.Color
import com.badlogic.gdx.graphics.g2d.TextureAtlas
import com.badlogic.gdx.graphics.g2d.TextureAtlas.AtlasRegion
import com.badlogic.gdx.utils.Array
import com.neutrino.game.graphics.textures.*

fun get(atlas: String, region: String): AtlasRegion {
	return Textures.atlases[atlas]!!.findRegion(region)
}

fun getArray(atlas: String, vararg regions: String): Array<AtlasRegion> {
	val textureArray: Array<AtlasRegion> = Array()
	for (region in regions) {
		textureArray.add(Textures.atlases[atlas]!!.findRegion(region))
	}
	return textureArray
}

for (atlas in Gdx.files.absolute("${Gdx.files.localStoragePath}/core/src/assets/textures").list(".atlas")) {
	Textures.atlases[atlas.nameWithoutExtension()] = TextureAtlas(atlas)
}

Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$1"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$2"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$3"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$4"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$5"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$6"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$7"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$8"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$9"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$10"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$11"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$12"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$13"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$14"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$15"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$16"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$17"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorBasic$18"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorCracked$1"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorCracked$2"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorCracked$3"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorCracked$4"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorSmaller$1"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorSmaller$2"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorSmaller$3"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorSmaller$4"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorSmaller$5"), z = 0)
Textures add TextureSprite(get("entities", "cleanDungeonFloorSmaller$6"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$1"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$2"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$3"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$4"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$5"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$6"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$7"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$8"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$9"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$10"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$11"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$12"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$13"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$14"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$15"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$16"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$17"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorBasic$18"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorCracked$1"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorCracked$2"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorCracked$3"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorCracked$4"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorLights$1"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorLights$2"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorLights$3"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorLights$4"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorLights$5"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorSmaller$1"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorSmaller$2"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorSmaller$3"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorSmaller$4"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorSmaller$5"), z = 0)
Textures add TextureSprite(get("entities", "dungeonFloorSmaller$6"), z = 0)
Textures add TextureSprite(get("entities", "dungeonStairsDown"), z = 0)
Textures add TextureSprite(get("entities", "dungeonStairsUp"), z = 0)
Textures add TextureSprite(get("entities", "stonePillar"), 2f, 10f)
Textures add TextureSprite(get("entities", "stonePillarCracked"), 2f, 10f)
Textures add TextureSprite(get("entities", "dungeonWall$1"), z = 0)
Textures add TextureSprite(get("entities", "dungeonWall$2"), z = 0)
Textures add TextureSprite(get("entities", "dungeonWall$3"), z = 0)
Textures add TextureSprite(get("entities", "dungeonWall$4"), z = 0)
Textures add TextureSprite(get("entities", "dungeonWall$5"), z = 0)
Textures add TextureSprite(get("entities", "dungeonWallInside"), z = 0)
Textures add TextureSprite(get("entities", "dungeonWallTop$1"), 0f, 21f)
Textures add TextureSprite(get("entities", "dungeonWallTop$2"), 0f, 21f)
Textures add TextureSprite(get("entities", "dungeonWallTop$3"), 0f, 21f)
Textures add TextureSprite(get("entities", "dungeonWallTop$4"), 0f, 21f)
Textures add TextureSprite(get("entities", "dungeonWallTop$5"), 0f, 21f)
Textures add TextureSprite(get("entities", "dungeonWallTopInside"), 0f, 16f)
Textures add TextureSprite(get("entities", "dungeonWallSide$1"))
Textures add TextureSprite(get("entities", "dungeonWallSide$2"))
Textures add TextureSprite(get("entities", "dungeonWallSide$3"))
Textures add TextureSprite(get("entities", "dungeonWallSide$4"))
Textures add TextureSprite(get("entities", "dungeonWallSide$5"))
Textures add TextureSprite(get("entities", "dungeonWallSideSmall$1"), 0f, 16f)
Textures add TextureSprite(get("entities", "dungeonWallSideSmall$2"), 0f, 16f)
Textures add TextureSprite(get("entities", "dungeonWallSideSmall$3"), 0f, 16f)
Textures add TextureSprite(get("entities", "dungeonWallSideSmall$4"), 0f, 16f)
Textures add TextureSprite(get("entities", "dungeonWallSideSmall$5"), 0f, 16f)
Textures add TextureSprite(get("entities", "woodenDoor"), 0f, 2f)
Textures add TextureSprite(get("entities", "woodenDoorClosed"))
Textures add TextureSprite(get("entities", "woodenDoorVertical"), 0f, 14f)
Textures add TextureSprite(get("entities", "woodenDoorVerticalClosed"), 13f)
Textures add TextureSprite(get("entities", "woodenDoorArched"), 0f, 2f)
Textures add TextureSprite(get("entities", "woodenDoorArchedClosed"))
Textures add TextureSprite(get("entities", "woodenDoorArchedVertical"), 0f, 14f)
Textures add TextureSprite(get("entities", "woodenDoorArchedVerticalClosed"), 13f)
Textures add TextureSprite(get("entities", "stonePillarTop"), 2f, 2f)
Textures add TextureSprite(get("entities", "candleSingle$1"), LightSources(Light(1f, 8f, Color.valueOf("e5842868"), 4f, 48f)), 10f, 8f)
Textures add TextureSprite(get("entities", "candleSingle$2"), LightSources(Light(1f, 6f, Color.valueOf("e5842868"), 4f, 48f)), 8f, 4f)
Textures add TextureSprite(get("entities", "candleSingle$3"), LightSources(Light(2f, 5f, Color.valueOf("f3642268"), 4f, 48f)), 7f, 3f)
Textures add TextureSprite(get("entities", "candleSingle$4"), LightSources(Light(2f, 8f, Color.valueOf("f3642268"), 4f, 48f)), 4f, 4f)
Textures add TextureSprite(get("entities", "candleSingle$5"), LightSources(Light(0f, 5f, Color.valueOf("dc5e2668"), 4f, 48f)), 11f, 11f)
Textures add TextureSprite(get("entities", "clayPot$1"), 1f, 3f)
Textures add TextureSprite(get("entities", "clayPot$2"), 0f, 5f)
Textures add TextureSprite(get("entities", "clayPot$3"), 4f, 4f)
Textures add TextureSprite(get("entities", "clayPot$4"), 2f, 8f)
Textures add TextureSprite(get("entities", "clayPot$1Destroyed"), 0f, 1f)
Textures add TextureSprite(get("entities", "clayPot$2Destroyed"), 1f, 2f)
Textures add TextureSprite(get("entities", "clayPot$3Destroyed"), 4f, 1f)
Textures add TextureSprite(get("entities", "clayPot$4Destroyed"), 2f, 1f)
Textures add AnimatedTextureSprite(getArray("entities", "standingTorch$1#1", "standingTorch$1#2", "standingTorch$1#3", ), true, 0.25f, LightSources(listOf(arrayListOf(
		Light(6f, 23f, Color.valueOf("f36422a2"), 12f, 512f),
	),arrayListOf(
		Light(6f, 23f, Color.valueOf("f36422a2"), 12f, 512f),
	),arrayListOf(
		Light(6f, 23f, Color.valueOf("f36422a2"), 12f, 512f),
	),)), 1f, 4f)
Textures add AnimatedTextureSprite(getArray("entities", "standingTorch$2#1", "standingTorch$2#2", "standingTorch$2#3", ), true, 0.25f, LightSources(listOf(arrayListOf(
		Light(6f, 21f, Color.valueOf("f36422a0"), 10f, 384f),
	),arrayListOf(
		Light(6f, 21f, Color.valueOf("f36422a0"), 10f, 384f),
	),arrayListOf(
		Light(6f, 21f, Color.valueOf("f36422a0"), 10f, 384f),
	),)), 1f, 4f)
Textures add AnimatedTextureSprite(getArray("entities", "torchFront#1", "torchFront#2", "torchFront#3", ), true, 0.25f, LightSources(listOf(arrayListOf(
		Light(2f, 7f, Color.valueOf("f3510783"), 6f, 128f),
	),arrayListOf(
		Light(2f, 7f, Color.valueOf("f3510783"), 6f, 128f),
	),arrayListOf(
		Light(2f, 7f, Color.valueOf("f3510783"), 6f, 128f),
	),)), 5f, 19f)
Textures add AnimatedTextureSprite(getArray("entities", "torchSide#1", "torchSide#2", "torchSide#3", ), true, 0.25f, LightSources(listOf(arrayListOf(
		Light(2f, 5f, Color.valueOf("f3510783"), 6f, 128f),
	),arrayListOf(
		Light(2f, 5f, Color.valueOf("f3510783"), 6f, 128f),
	),arrayListOf(
		Light(2f, 5f, Color.valueOf("f3510783"), 6f, 128f),
	),)), -1f, 3f)
Textures add TextureSprite(get("entities", "barrel"), 3f, 1f)
Textures add TextureSprite(get("entities", "barrelDestroyed"), 0f, 1f)
Textures add TextureSprite(get("entities", "crateBiggerDark"), 2f)
Textures add TextureSprite(get("entities", "crateBiggerDarkDestroyed"))
Textures add TextureSprite(get("entities", "crateSmall"), 3f)
Textures add TextureSprite(get("entities", "crateSmallDestroyed"))
Textures add TextureSprite(get("entities", "woodenChestMid"), 1f, 1f)
Textures add TextureSprite(get("items", "basicFireWand"), 3f, 3f)
Textures add TextureSprite(get("items", "basicPoisonWand"), 4f, 4f)
Textures add TextureSprite(get("items", "bigBow"), 1f, 1f)
Textures add TextureSprite(get("items", "book"), 2f)
Textures add TextureSprite(get("items", "brokenSword"), 4f, 3f)
Textures add TextureSprite(get("items", "cuffedLinenPants"), 3f, 3f)
Textures add TextureSprite(get("items", "curvedBow"), 5f, 2f)
Textures add TextureSprite(get("items", "dagger"), 4f, 4f)
Textures add TextureSprite(get("items", "extinguishedFireWand"), 4f, 4f)
Textures add TextureSprite(get("items", "fireStaff"), 1f, 1f)
Textures add TextureSprite(get("items", "gold1"), 5f, 6f)
Textures add TextureSprite(get("items", "gold2"), 3f, 4f)
Textures add TextureSprite(get("items", "gold3"), 2f, 2f)
Textures add TextureSprite(get("items", "gold4"), 2f, 2f)
Textures add TextureSprite(get("items", "gold5"), 5f, 5f)
Textures add TextureSprite(get("items", "gold6"), 2f, 4f)
Textures add TextureSprite(get("items", "gold7"), 1f, 3f)
Textures add TextureSprite(get("items", "gold8"), 2f, 2f)
Textures add TextureSprite(get("items", "knife"), 2f, 2f)
Textures add TextureSprite(get("items", "leatherBoots"), 0f, 3f)
Textures add TextureSprite(get("items", "leatherCap"), 2f, 4f)
Textures add TextureSprite(get("items", "leatherJacket"), 2f, 2f)
Textures add TextureSprite(get("items", "leatherSocks"), 1f, 6f)
Textures add TextureSprite(get("items", "linenShirt"), 2f, 3f)
Textures add TextureSprite(get("items", "meat"), 2f, 3f)
Textures add TextureSprite(get("items", "pocketKnife"), 5f, 4f)
Textures add TextureSprite(get("items", "reinforcedLeatherBoots"))
Textures add TextureSprite(get("items", "reinforcedLeatherCap"), 4f, 3f)
Textures add TextureSprite(get("items", "rippedPants"), 4f, 4f)
Textures add TextureSprite(get("items", "rockWand"), 4f, 4f)
Textures add TextureSprite(get("items", "scrollOfDefence"), 1f, 1f)
Textures add TextureSprite(get("items", "scrollOfFireball"), 1f, 1f)
Textures add TextureSprite(get("items", "scrollOfTeleportation"), 1f, 1f)
Textures add TextureSprite(get("items", "smallBackpack"), 4f, 3f)
Textures add TextureSprite(get("items", "smallBag"), 3f, 2f)
Textures add TextureSprite(get("items", "smallBow"), 5f, 2f)
Textures add TextureSprite(get("items", "smallHealingPotion"), 4f, 2f)
Textures add TextureSprite(get("items", "tornShirt"), 2f, 3f)
Textures add TextureSprite(get("items", "woodenFlipFlops"), 2f, 3f)
Textures add TextureSprite(get("items", "sword"), 2f, 2f)
Textures add AnimatedTextureSprite(getArray("characters", "playerWalk#1", "playerWalk#2", "playerWalk#3", "playerWalk#4", "playerWalk#5", "playerWalk#6"), true, 0.2f, 7f)
Textures add AnimatedTextureSprite(getArray("characters", "playerCrouch#2", "playerCrouch#3", "playerCrouch#1", "playerCrouch#4"), false, 0.2f, 5f)
Textures add AnimatedTextureSprite(getArray("characters", "playerIdleFight#1", "playerIdleFight#2", "playerIdleFight#3", "playerIdleFight#4", "playerIdleFight#5", "playerIdleFight#6"), true, 0.2f, 4f)
Textures add AnimatedTextureSprite(getArray("characters", "playerIdle#1", "playerIdle#2", "playerIdle#3", "playerIdle#4", "playerIdle#5", "playerIdle#6", "playerIdle#7"), true, 0.2f, 5f)
Textures add AnimatedTextureSprite(getArray("characters", "playerAttack#2", "playerAttack#3", "playerAttack#4", "playerAttack#5"), false, 0.2f, 7f)
Textures add AnimatedTextureSprite(getArray("characters", "playerAttack2#2", "playerAttack2#3", "playerAttack2#4", "playerAttack2#5", "playerAttack2#6"), false, 0.2f, -5f)
Textures add AnimatedTextureSprite(getArray("characters", "playerAttack3#1", "playerAttack3#2", "playerAttack3#3", "playerAttack3#4", "playerAttack3#5", "playerAttack3#6"), false, 0.2f, -8f)
Textures add AnimatedTextureSprite(getArray("characters", "playerCast#1", "playerCast#2", "playerCast#3", "playerCast#4", "playerCast#5"), false, 0.2f, 5f)
Textures add AnimatedTextureSprite(getArray("characters", "playerCastLong#1", "playerCastLong#2", "playerCastLong#3", "playerCastLong#4", "playerCastLong#5", "playerCastLong#6", "playerCastLong#7", "playerCastLong#8"), false, 0.2f, 5f)
Textures add AnimatedTextureSprite(getArray("characters", "playerHurt#1", "playerHurt#2", "playerHurt#3"), false, 0.2f, 6f)
Textures add AnimatedTextureSprite(getArray("characters", "playerDeath#1", "playerDeath#2", "playerDeath#3", "playerDeath#4", "playerDeath#5", "playerDeath#6"), false, 0.2f, 6f)
Textures add AnimatedTextureSprite(getArray("characters", "playerItem#1", "playerItem#2", "playerItem#3", "playerItem#4"), false, 0.2f, 5f)
Textures add AnimatedTextureSprite(getArray("characters", "playerPunch#1", "playerPunch#2", "playerPunch#3", "playerPunch#4"), false, 0.2f, 5f)
Textures add AnimatedTextureSprite(getArray("characters", "playerPunch2#1", "playerPunch2#2", "playerPunch2#3", "playerPunch2#4", "playerPunch2#5"), false, 0.2f, 3f)
Textures add AnimatedTextureSprite(getArray("characters", "playerPunch3#1", "playerPunch3#2", "playerPunch3#3", "playerPunch3#4"), false, 0.2f, 6f)
Textures add AnimatedTextureSprite(getArray("characters", "playerKick#1", "playerKick#2", "playerKick#3", "playerKick#4"), false, 0.2f, 7f)
Textures add AnimatedTextureSprite(getArray("characters", "playerKick2#1", "playerKick2#2", "playerKick2#3", "playerKick2#4"), false, 0.2f, 1f)
Textures add AnimatedTextureSprite(getArray("characters", "playerRun#1", "playerRun#2", "playerRun#3", "playerRun#4", "playerRun#5", "playerRun#6"), true, 0.2f, 4f)
Textures add AnimatedTextureSprite(getArray("characters", "playerBow#1", "playerBow#2", "playerBow#3", "playerBow#4", "playerBow#5", "playerBow#6"), false, 0.2f)
Textures add AnimatedTextureSprite(getArray("characters", "mouseIdle#1", "mouseIdle#2", "mouseIdle#3", "mouseIdle#4", "mouseIdle#5", "mouseIdle#6", "mouseIdle#7", "mouseIdle#8"), true, 0.25f)
Textures add AnimatedTextureSprite(getArray("characters", "mouseWalk#1", "mouseWalk#2", "mouseWalk#3", "mouseWalk#4"), true, 0.25f)
Textures add AnimatedTextureSprite(getArray("characters", "mouseAttack#1", "mouseAttack#2", "mouseAttack#3", "mouseAttack#4"), false, 0.25f)
Textures add AnimatedTextureSprite(getArray("characters", "mouseDeath#1", "mouseDeath#2", "mouseDeath#3", "mouseDeath#4"), false, 0.25f)
Textures add AnimatedTextureSprite(getArray("characters", "slimeIdle#1", "slimeIdle#2", "slimeIdle#3", "slimeIdle#4", "slimeIdle#5", "slimeIdle#6"), true, 0.25f)
Textures add AnimatedTextureSprite(getArray("characters", "slimeWalk#1", "slimeWalk#2", "slimeWalk#3", "slimeWalk#4", "slimeWalk#5", "slimeWalk#6", "slimeWalk#7", "slimeWalk#8"), true, 0.2f)
Textures add AnimatedTextureSprite(getArray("characters", "slimeAttack#1", "slimeAttack#2", "slimeAttack#3", "slimeAttack#4", "slimeAttack#5", "slimeAttack#6"), false, 0.25f)
Textures add AnimatedTextureSprite(getArray("characters", "slimeDeath#1", "slimeDeath#2", "slimeDeath#3", "slimeDeath#4"), false, 0.25f)
Textures add TextureSprite(get("items", "strengthBook"), 2f)
Textures add TextureSprite(get("items", "strengthBook1"), 2f)
Textures add TextureSprite(get("items", "strengthBook2"), 2f)
Textures add TextureSprite(get("items", "strengthBook3"), 2f)
Textures add TextureSprite(get("items", "strengthBook4"), 2f)
Textures add TextureSprite(get("items", "strengthBook5"), 2f)
Textures add TextureSprite(get("items", "strengthBook6"), 2f)
Textures add TextureSprite(get("items", "strengthBook7"), 2f)
Textures add TextureSprite(get("items", "defenceBook"), 2f)
Textures add TextureSprite(get("items", "defenceBook1"), 2f)
Textures add TextureSprite(get("items", "defenceBook2"), 2f)
Textures add TextureSprite(get("items", "defenceBook3"), 2f)
Textures add TextureSprite(get("items", "defenceBook4"), 2f)
Textures add TextureSprite(get("items", "defenceBook5"), 2f)
Textures add TextureSprite(get("items", "defenceBook6"), 2f)
Textures add TextureSprite(get("items", "defenceBook7"), 2f)
Textures add TextureSprite(get("items", "rogueBook"), 2f)
Textures add TextureSprite(get("items", "rogueBook1"), 2f)
Textures add TextureSprite(get("items", "rogueBook2"), 2f)
Textures add TextureSprite(get("items", "rogueBook3"), 2f)
Textures add TextureSprite(get("items", "rogueBook4"), 2f)
Textures add TextureSprite(get("items", "rogueBook5"), 2f)
Textures add TextureSprite(get("items", "rogueBook6"), 2f)
Textures add TextureSprite(get("items", "rogueBook7"), 2f)
Textures add TextureSprite(get("items", "rangedBook"), 2f)
Textures add TextureSprite(get("items", "rangedBook1"), 2f)
Textures add TextureSprite(get("items", "rangedBook2"), 2f)
Textures add TextureSprite(get("items", "rangedBook3"), 2f)
Textures add TextureSprite(get("items", "rangedBook4"), 2f)
Textures add TextureSprite(get("items", "rangedBook5"), 2f)
Textures add TextureSprite(get("items", "rangedBook6"), 2f)
Textures add TextureSprite(get("items", "rangedBook7"), 2f)
Textures add TextureSprite(get("iconsSkills", "skilBlock"))
Textures add TextureSprite(get("iconsSkills", "skillActiveShield"))
Textures add TextureSprite(get("iconsSkills", "skillBerserk"))
Textures add TextureSprite(get("iconsSkills", "skillDualWield"))
Textures add TextureSprite(get("iconsSkills", "skillDualWield2"))
Textures add TextureSprite(get("iconsSkills", "skillFocus"))
Textures add TextureSprite(get("iconsSkills", "skillIncreaseArrowDamage"))
Textures add TextureSprite(get("iconsSkills", "skillIncreaseMeleeDamage"))
Textures add TextureSprite(get("iconsSkills", "skillIncreaseOnehandedDamage"))
Textures add TextureSprite(get("iconsSkills", "skillIncreaseShieldDefence"))
Textures add TextureSprite(get("iconsSkills", "skillIncreaseTwohandedDamage"))
Textures add TextureSprite(get("iconsSkills", "skillLastManStanding"))
Textures add TextureSprite(get("iconsSkills", "skillParry"))
Textures add TextureSprite(get("iconsSkills", "skillSilentWalk"))
Textures add TextureSprite(get("iconsSkills", "skillThorns"))
Textures add TextureSprite(get("iconsSkills", "skillBleed"))
Textures add TextureSprite(get("iconsSkills", "skillCripplingShot"))
Textures add TextureSprite(get("iconsSkills", "skillCripplingSpin"))
Textures add TextureSprite(get("iconsSkills", "skillDaggerThrow"))
Textures add TextureSprite(get("iconsSkills", "skillExecution"))
Textures add TextureSprite(get("iconsSkills", "skillGutAttack"), LightSources(arrayListOf(
	Light(11f, 13f, Color.valueOf("983028ff"), 5f, 64f),
	Light(13f, 11f, Color.valueOf("983028ff"), 5f, 64f),
	Light(8f, 10f, Color.valueOf("983028ff"), 5f, 64f),
	Light(10f, 8f, Color.valueOf("983028ff"), 5f, 64f),
	Light(5f, 7f, Color.valueOf("983028ff"), 5f, 64f),
	Light(7f, 5f, Color.valueOf("983028ff"), 5f, 64f),
	Light(2f, 4f, Color.valueOf("983028ff"), 5f, 64f),
	Light(4f, 2f, Color.valueOf("983028ff"), 5f, 64f),
),))
Textures add TextureSprite(get("iconsSkills", "skillLuckyClover"))
Textures add TextureSprite(get("iconsSkills", "skillShadowCloak"))
Textures add TextureSprite(get("iconsSkills", "skillShieldBash"))
Textures add TextureSprite(get("iconsSkills", "skillTeleport"))
Textures add TextureSprite(get("iconsSkills", "skillTeleportBackstab"))
Textures add TextureSprite(get("iconsSkills", "skillTwoshot"))
Textures add TextureSprite(get("iconsSkills", "heart"), 2f, 2f)
Textures add TextureSprite(get("iconsSkills", "itemBetter"), 4f, 4f)
Textures add TextureSprite(get("iconsSkills", "itemWorse"), 4f, 4f)
Textures add AnimatedTextureSprite(getArray("iconsSkills", "threeDots#1", "threeDots#2", "threeDots#3", "threeDots#4"), true, 0.5f)
Textures add AnimatedTextureSprite(getArray("iconsSkills", "exclamationMark#1", "exclamationMark#2", "exclamationMark#3", "exclamationMark#4", "exclamationMark#5", "exclamationMark#6"), false, 0.16666667f)
Textures add TextureSprite(get("projectiles", "fireProjectile"), LightSources(arrayListOf(
	Light(3f, 2f, Color.valueOf("f36422ff"), 5f, 64f),
	Light(7f, 1f, Color.valueOf("f35107ff"), 5f, 64f),
),), z = 2)
Textures add TextureSprite(get("projectiles", "poisonProjectile"), LightSources(arrayListOf(
	Light(2f, 2f, Color.valueOf("378021ff"), 5f, 64f),
	Light(7f, 2f, Color.valueOf("61961bff"), 5f, 64f),
),), z = 2)
Textures add TextureSprite(get("projectiles", "woodenArrow"), z = 2)