package com.neutrino.game.map.generation.util

import com.neutrino.game.entities.Items
import com.neutrino.game.entities.items.Item
import com.neutrino.game.map.generation.TagParams
import com.neutrino.game.util.EntityName
import com.neutrino.game.utility.Probability
import kotlin.random.Random

class ItemPool(
    private val items: MutableMap<Int, ArrayList<Probability<EntityName>>>
) {

    private val probabilitySum: MutableMap<Int, Float> = mutableMapOf()

    init {
        for (tier in items) {
            var sum = 0f
            tier.value.forEach { sum += it.probability }
            probabilitySum[tier.key] = sum
        }
    }

    fun getRandomItem(tier: Int, rng: Random, params: TagParams): Item? {
        if (probabilitySum[tier] == null)
            return null
        var random = rng.nextFloat() * probabilitySum[tier]!! / params.itemQuality
        if (random >= probabilitySum[tier]!!)
            random = probabilitySum[tier]!! - 0.000001f
        var sum = 0f
        for (item in items[tier]!!) {
            if (random < item.probability + sum) {
                return Items.new(item.value)
            }
            sum += item.probability
        }
        throw Exception("An item should be generated by now")
    }
}